apiVersion: v1
data:
  session_secret: Q0J6Ty96L2hiL05aNTNZUjFJNTdiYmVEYjdIU2I0YXVEZzZmVFIxbDZGSUVFakFZTTl6UnNVL0ZqUT09
kind: Secret
metadata:
  name: spring-boot-proxy
  namespace: test
type: Opaque
